name: CI/CD

on: pull_request

jobs:
  test:
    environment: CI
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ["codellama", "llama-2", "mistral"]
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_ENVIRONMENT: ci-cd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal pyyaml

      - name: Prep config and data for CI
        run: |
          python ci/prep_for_ci.py --config=config/${{ matrix.config }}.yml --data=data/sqlqa.jsonl

      - name: Run training job on Modal
        run: |
          GPU_MEM=40 modal run src.train --config=config/${{ matrix.config }}.yml --data=data/sqlqa.jsonl
